repos:

- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    language: system

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.740
  hooks:
  - id: mypy
    exclude: '^(doc/)|(tests/)'

- repo: git://github.com/guykisel/prospector-mirror
  rev: 7ff847e779347033ebbd9e3b88279e7f3a998b45
  hooks:
  - id: prospector
    additional_dependencies: ['pytest']
    exclude: '^(doc/)|(tests/)|(tests/bar/)|(tests/baz/)'
