repos:

- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.740
  hooks:
  - id: mypy
    exclude: '^(doc/)|(tests/)'

- repo: https://github.com/PyCQA/prospector
  rev: 1.1.7
  hooks:
  - id: prospector
    additional_dependencies: ['pytest']
    exclude: '^(doc/)|(tests/)|(tests/bar/)|(tests/baz/)'
