language: python
cache: pip
python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install .[test,precommit]

# run tests
script:
    - pre-commit run --all-files
    - cd tests
    - pytest
