language: python
cache: pip
python:

jobs:
    include:
    - python: "2.7"
      env: INSTALL_TYPE="test_pypi" TEST_TYPE="test"
    - python: "3.5"
      env: INSTALL_TYPE="test_pypi" TEST_TYPE="test"
    - python: "3.6"
      env: INSTALL_TYPE="test_sdist" TEST_TYPE="test"
    - python: "3.7"
      env: INSTALL_TYPE="test_sdist" TEST_TYPE="test"
    - python: "3.8"
      env: INSTALL_TYPE="test_sdist" TEST_TYPE="test"
    - python: "3.6"
      env: INSTALL_TYPE="test" TEST_TYPE="test"
    - python: "3.7"
      env: INSTALL_TYPE="test" TEST_TYPE="test"
    - python: "3.8"
      env: INSTALL_TYPE="test" TEST_TYPE="test"
    - python: "3.7"
      env: INSTALL_TYPE="precommit" TEST_TYPE="precommit"

install:
    - ./.ci/install_script.sh

# run tests
script:
    - ./.ci/test_script.sh
